### PR TITLE
Add static data for testnet + static data generation

### PR DESCRIPTION
**Pull request by tifrel**

### CODE REVIEW

**Review by sainthiago — COMMENTED** [review]
👍

**Comment by bh2smith** [comment]
1. The source file references weren't updated (reverting this change) https://github.com/bh2smith/zerion-sdk/pull/14
2. This PR wasn't squash merged. Looks like shit in the [commit history](https://github.com/bh2smith/zerion-sdk/commits/main/).

**Comment by tifrel** [comment]
Regarding 2., you (and it seems only you) can change that in the project settings.

**Comment by bh2smith** [comment]
Have disabled the possibility to merge like this in the future.

**Pull request merged**
